version: 2
jobs:
    git_clone_all:
        machine:
            enabled: true
        steps:
            - checkout
            - run:
                name: Get_Submodules
                command: git submodule init && git submodule update
    build:
        machine:
            enabled: true
        steps:
            - run:
                name: Build_All
                command: make
    test:
        machine:
            enabled: true
        steps:
            - run:
                name: Run_Test
                command: ./run_test.sh
workflows:
    version: 2
    git_clone:
        jobs:
            - git_clone_all
    build_and_test:
        jobs:
            - build
            - test

