version: 2
jobs:
    build_and_test:
        machine:
            image: ubuntu-1604:201903-01
            enabled: true
        steps:
            - checkout
            #- run:
              #  name: Get_Submodules
              #  command: ./get_submodules.sh
            - run:
                name: Install Prerequisites
                command: |
                    sudo apt update
                    sudo apt install python python-pip
                    sudo pip install -U pip
                    sudo pip install pipenv
                    pipenv install pytest
                    pipenv install pytest-html
                    #sudo apt install libunwind-dev golang-go
            - run:
                name: Build_All
                command: make NOSAN=1 -j 2 test_bin
            - run:
                name: Run_Test
                command: |
                    pipenv run ./run_test.sh test/test_openssl_version.py
            - store_artifacts:
                path: ./report
workflows:
    version: 2
    Run_TalkWithTLS:
        jobs:
            - build_and_test
