version: 2
jobs:
    build_and_test:
        machine:
            enabled: true
        steps:
            - checkout
            - run:
                name: Get_Submodules
                command: git submodule init && git submodule update
            - run:
                name: Build_All
                command: make
            - run:
                command: |
                    sudo pip install pipenv
                    pipenv install pytest
                    pipenv install pytest-html
            - run:
                name: Run_Test
                command: pipenv run ./run_test.sh
workflows:
    version: 2
    Run_TalkWithTLS:
        jobs:
            - build_and_test

